### ISSUE TITLE
Submitted order -Recent submitted orders

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#150]
The button is not working

**Credential**
UAT version-3(7)
Username: obadare.inspector@gmail.com
Password: testing1234

Video: https://drive.google.com/file/d/1Gjy-5YDhldoCCu6v1LutLdyv9AcF86yt/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and now its not a link, its just an heading.
when user searches with the dates, order number. it will display the order under recent submitted orders.
**but recent submitted orders is something that the orders are recently submitted and should be be auto populated instead of search..**
https://drive.google.com/file/d/18-x01jw8R02HtOfqumadzWXeJq8duOkL/view?usp=drive_link

**Comment by himashree2024** [comment]
tested and observed the recent submitted orders link option is removed. 

![Image](https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/25821736-d6d8-41cf-8ed9-e630f887db8e)
