### ISSUE TITLE
Dashboard- View Online Inspector

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#88]
"User is able to view only few online inspectors, as the rest below are seen only when user decreases the page size, there should be a pagedown scroll to view the data which is downside."

**Credential** 
URL: https://obadare.irisnextgen.com/business/system-management/group-user-management 
Username: nguyenletu2010@gmail.com
Pwd: Nguyenletu2001 

Video: https://drive.google.com/file/d/19y8htYXDZxxuwMgWl-Fz-iDU4GliSniH/view?usp=drive_link

**Comment by himashree2024** [comment]
tested and scroll bar is implemented but it is only for the online inspector tab which is hardly visible and also if the system tab from menu bar is clicked or expanded the online inspector tab is out of the screen which can't be seen. 
So, the scroll bar should be implemented in whole menu bar so that when any tab in menu bar is expanded all the options can be seen when scrolling. 

Video Reference: https://drive.google.com/file/d/1NPoj3XhshWGhKD_Zq-tF20d05ZTQY8qv/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and is working fine in UAT.


https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/39b5a700-92fd-4f1d-a704-78d8fae75400
