### ISSUE TITLE
Blank order- Delete blank orders

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#97]
"Tested and is working fine for some of the blank orders. 
But ""An error occurred while updating the enteries, see the inner exception for details"" error message is getting displayed when user tries to delete some of the blank order."

**Credential** 
URL: https://obadare.irisnextgen.com/business/system-management/group-user-management 
Username: nguyenletu2010@gmail.com
Pwd: Nguyenletu2001

Video: https://drive.google.com/file/d/1_250t4xvKNZjq5EAK-4HSLglCl5eXftO/view?usp=drive_link
https://drive.google.com/file/d/1wJVpvfocHgOi19WKVS8r8ztCQrLEemgt/view?usp=drive_link

**Comment by himashree2024** [comment]
Could not test it because there are no blank orders in the web app when tried to create from the mobile app it still has the old version i.e.3(7). User can create blank orders through inspection order tab but those orders are not reflected in web app. 

Reference: 

![Image](https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/7bbadf25-c18b-46c6-aff4-31c50afe1bf3)




![Image](https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/cb25673c-35a5-4bb8-9017-bf4e3ef73ccb)

**Comment by himashree2024** [comment]
Tested and is working fine.


https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/518fbdb7-0164-48c6-a98e-d51e89c00281
