### ISSUE TITLE
Blank order- Filter By PIC

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#99]
When user filters on the PIC few list of orders are getting displayed but there is no PIC name getting displayed under that column so that user can verify it.

**Credential** 
URL: https://obadare.irisnextgen.com/business/system-management/group-user-management 
Username: nguyenletu2010@gmail.com
Pwd: Nguyenletu2001

Video: https://drive.google.com/file/d/1_PM8nJd_LoeJbNEVfNxNhfhWNye-1UPJ/view?usp=drive_link

**Comment by himashree2024** [comment]
Could not test it because there are no blank orders in the web app when tried to create from the mobile app it still has the old version i.e.3(7). User can create blank orders through inspection order tab but those orders are not reflected in web app. 

Reference: 

![Image](https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/7bbadf25-c18b-46c6-aff4-31c50afe1bf3)




![Image](https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/cb25673c-35a5-4bb8-9017-bf4e3ef73ccb)

**Comment by himashree2024** [comment]
Tested and observed that the filter is not making any sense here.
when clicked on the created by, it gives two dropdowns, 1st dropdown with options match any or match all. 2nd dropdown with label as **Any** and the dropdown contains the tech names, so what is the user of match all and match any when there is a dropdown for tech.


https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/03bddfda-0b55-4e7c-97ef-703c254df51b

**Comment by himashree2024** [comment]
Tested and observed that When filtered on Tech, The filter is getting auto applied as soon as user selects the tech from the dropdown before clicking on Apply button.
Video: 

https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/992ee3a5-b1b1-453b-819d-b3802b34227d

**Comment by himashree2024** [comment]
Tested and observed that when user selects any Tech from the dropdown under tech filter, the list is getting filtered automatically even before user clicks on apply button. 


https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/dff4c663-abbd-49f1-bb7c-d47dce66a656

**Comment by himashree2024** [comment]
Closing this bug as we already have bug no 228 for filter
